name: Testing dir2cast
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['7.3', '7.4', '8.0', '8.1', '8.2']
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Setup PHP and extensions
        uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring
          coverage: xdebug
          tools: php-cs-fixer
        env:
          fail-fast: true
      - name: Checkout
        uses: actions/checkout@v3
      - name: Composer Install
        uses: ramsey/composer-install@v2
        with:
          working-directory: "test"
      - name: Test with phpunit (MacOS, Linux)
        if: ${{ ! contains(matrix.operating-system, 'windows') }}
        run: ./test/run.sh --do-not-cache-result .
      - name: Test with phpunit (Windows)
        if: ${{ contains(matrix.operating-system, 'windows') }}
        run: cd test ; vendor\bin\phpunit --bootstrap "bootstrap.php" .

